# Git details
$gitBranch = (git rev-parse --abbrev-ref HEAD)
$gitCommit = (git rev-parse HEAD).Substring(0, 10)
$buildDate = Get-Date -Format 'yyyy/MM/dd HH:mm:ss'

$fileContent = "
// this file is automatically generated by build script
export const GitVersion = {
  revision: '$gitCommit',
  branch: '$gitBranch',
  buildDate: '$buildDate'
};
"
Write-Output $fileContent | Out-File 'src/environments/buildInfo.ts' -Encoding ascii
